### ISSUE TITLE
window 上 运行 fis-config.js 远端linux上生成文件路径不对

### ISSUE THREAD

**Issue by shekobe** [2betop/fis3-deploy-sftp#3]
配置文件：

```
fis.media("rd").set("project.files",["./view/admin/release/list.html","./view/admin/release/index.html","./src/admin/controller/socket.js"]).set("project.ignore", ["{node_modules}/**",".*","package.json","fis-conf.js","gulpfile.js"])
.match("{/view/admin/release/list.html,/view/admin/release/index.html,/src/admin/controller/socket.js}", {
    deploy: fis.plugin('sftp', {
        // sftp路径
        to: '/home/suguiyun/test',

        // 参考 npm ssh2 的配置
        host: '10.100.14.21',
        username: 'xxxx',
        password: '******'
    })
    
});
```

运行结果：
try to connect to 10.100.14.21:22
Client :: ready
SFTP :: ready

 - [14:37:55] view/admin/release/list.html >> \home\suguiyun\test\view\admin\release\list.html
 - [14:37:55] view/admin/release/index.html >> \home\suguiyun\test\view\admin\release\index.html
 - [14:37:55] src/admin/controller/socket.js >> \home\suguiyun\test\src\admin\controller\socket.js

**Comment by 2betop** [comment]
只支持 mac, 其他设备，请提 qr

**Comment by shekobe** [comment]
linux希望也能支持哦，大多数人会部署在上面

**Comment by 2betop** [comment]
大致问题是 path.join在 windows 上后变成 `\` 了，所以需要转成 `/`，没有测试环境我就不弄了，你自己倒腾吧。

**Comment by shekobe** [comment]
转成 /以后还报错

Client :: ready
SFTP :: ready
filepath /home/suguiyun/test/view/admin/release/list.html

E:\360shoujisvn3\qikuweb\node_modules\fis3-deploy-sftp\index.js:129
          throw new Error(error);
          ^

Error: Error: No such file
    at WriteStream.<anonymous> (E:\360shoujisvn3\qikuweb\node_modules\fis3-deploy-sftp\index.js:129:17)
    at emitOne (events.js:101:20)
    at WriteStream.emit (events.js:188:7)
    at E:\360shoujisvn3\qikuweb\node_modules\fis3-deploy-sftp\node_modules\ssh2-streams\lib\sftp.js:2848:12
    at SFTPStream._transform (E:\360shoujisvn3\qikuweb\node_modules\fis3-deploy-sftp\node_modules\ssh2-streams\lib\sftp.js:410:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (E:\360shoujisvn3\qikuweb\node_modules\fis3-deploy-sftp\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
